<a href="https://colab.research.google.com/github/hung1012/ML-Basics/blob/main/Numpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


# Creatting Numpy Array from Python List


In [ ]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [ ]:
np.array([3.14, 2, 3, 5])

array([3.14, 2.  , 3.  , 5.  ])

In [ ]:
np.array([1,2,3.4], dtype ='float')

array([1. , 2. , 3.4])

In [ ]:
a1 = np.array([1,2,3,4])

In [ ]:
type(a1)

numpy.ndarray

In [ ]:
a1.shape

(4,)

In [ ]:
a1.ndim


1

In [ ]:
a1.size

4

## Creating Numpy Array from Scratch
## zeros, one, full, arange, linspace

In [ ]:
np.zeros([2, 4], dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
np.ones([3, 5], dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
#Creating an array filled with a linear sequence
#Staring at 0, ending at 20, stepping by 2
#This is similar to the built-in rande() function
np.arange(0, 20, 2)


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.full((3,5), 6.9)

array([[6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9]])

In [ ]:
# Crate an array of five values evenly spaces between 0 and 1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# Random function

In [ ]:
#Seed for reproducibility
np.random.seed(0)
np.random.random((4,4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [ ]:
np.random.normal(0,1, (3,3))

array([[ 0.44386323,  0.33367433,  1.49407907],
       [-0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 ]])

In [ ]:
np.random.randint(0,10, (6,5))

array([[7, 4, 6, 7, 6],
       [7, 4, 6, 7, 9],
       [8, 5, 3, 7, 4],
       [5, 2, 4, 5, 2],
       [3, 4, 4, 9, 7],
       [1, 5, 3, 8, 9]])

# Array Indexing & Slicing

# One-dimensional subarray

In [ ]:
x1 = np.random.randint(20, size = 6)
x1

array([ 3,  4, 14, 14, 18, 16])

In [ ]:
x1[4], x1[0], x1[-1]



(16, 14, 8)

In [ ]:
x2 = np.random.randint(10, size =(3,4))
x2

array([[7, 9, 6, 7],
       [2, 0, 9, 3],
       [3, 5, 3, 7]])

In [ ]:
x2[1,2] = 6
x2

array([[7, 9, 6, 7],
       [2, 0, 6, 3],
       [3, 5, 3, 7]])

# Slicing

In [ ]:
x1

array([ 3,  4, 14, 14, 18, 16])

In [ ]:
x1[0:3]

array([14,  9,  6])

In [ ]:
x1[2:4]

array([ 6, 11])

In [ ]:
#every other element, every 2 steps
x1[::2]

array([14,  6, 16])

In [ ]:
x2


array([[7, 9, 6, 7],
       [2, 0, 6, 3],
       [3, 5, 3, 7]])

In [ ]:
#two rows and three colums
x2[:2,:3]

array([[7, 9, 6],
       [2, 0, 6]])

# Reshaping of Arrays and Transpose

In [ ]:
grid = np.arange(1,10)
grid.shape

(9,)

In [ ]:
grid.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
x = np.array([1,2,3])
x.shape

(3,)

In [ ]:
x.reshape(1,3).shape

(1, 3)

In [ ]:
x = np.arange(1,5, dtype = float)
x = x.reshape(2,2)
x

array([[1., 2.],
       [3., 4.]])

In [ ]:
x.T

array([[1., 3.],
       [2., 4.]])

# Array Concatenation and Splitting

In [ ]:
x = np.array([1,2,3])
y = np.array([3,2,1])

NameError: ignored

In [ ]:
np.concatenate((x,y), axis = 0)

In [ ]:
grid = np.array([[1,2,3],
               [4,5,6]])

In [ ]:
grid

In [ ]:
np.concatenate((grid,grid))

In [ ]:
#vstack
x = np.array([1,2,3])
grid = np.array([[9,8,7],
                 [6,5,4]])

In [ ]:
np.vstack((x, grid))

In [ ]:
#hstack
y = np.array([[99],
              [99]])
np.hstack((y, grid))

# Spliting of arrays

In [ ]:
x = np.array([1,2,3,99,69,3,2,1])

In [ ]:
x1, x2, x3 = np.split(x, [3,5])

In [ ]:
x1

array([1, 2, 3])

In [ ]:
x2

array([99, 69])

In [ ]:
x3

array([3, 2, 1])