<a href="https://colab.research.google.com/github/hung1012/ML-Basics/blob/main/Numpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


# Creatting Numpy Array from Python List


In [ ]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [ ]:
np.array([3.14, 2, 3, 5])

array([3.14, 2.  , 3.  , 5.  ])

In [ ]:
np.array([1,2,3.4], dtype ='float')

array([1. , 2. , 3.4])

In [ ]:
a1 = np.array([1,2,3,4])

In [ ]:
type(a1)

numpy.ndarray

In [ ]:
a1.shape

(4,)

In [ ]:
a1.ndim


1

In [ ]:
a1.size

4

## Creating Numpy Array from Scratch
## zeros, one, full, arange, linspace

In [ ]:
np.zeros([2, 4], dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
np.ones([3, 5], dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
#Creating an array filled with a linear sequence
#Staring at 0, ending at 20, stepping by 2
#This is similar to the built-in rande() function
np.arange(0, 20, 2)


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.full((3,5), 6.9)

array([[6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9]])

In [ ]:
# Crate an array of five values evenly spaces between 0 and 1
np.linspace(0,1,9)

array([0.   , 0.125, 0.25 , 0.375, 0.5  , 0.625, 0.75 , 0.875, 1.   ])

# Random function

In [ ]:
#Seed for reproducibility
np.random.seed(0)
np.random.random((4,4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [ ]:
np.random.normal(0,1, (3,3))

array([[ 0.44386323,  0.33367433,  1.49407907],
       [-0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 ]])

In [ ]:
np.random.randint(0,10, (6,5))

array([[7, 2, 0, 0, 4],
       [5, 5, 6, 8, 4],
       [1, 4, 9, 8, 1],
       [1, 7, 9, 9, 3],
       [6, 7, 2, 0, 3],
       [5, 9, 4, 4, 6]])

# Array Indexing & Slicing

# One-dimensional subarray

In [ ]:
x1 = np.random.randint(20, size = 6)
x1

array([ 4, 15,  3, 12,  4,  8])

In [ ]:
x1[4], x1[0], x1[-1]



(4, 4, 8)

In [ ]:
x2 = np.random.randint(10, size =(3,4))
x2

array([[4, 3, 7, 5],
       [5, 0, 1, 5],
       [9, 3, 0, 5]])

In [ ]:
x2[1,2] = 6
x2

array([[4, 3, 7, 5],
       [5, 0, 6, 5],
       [9, 3, 0, 5]])

# Slicing

In [ ]:
x1

array([ 4, 15,  3, 12,  4,  8])

In [ ]:
x1[0:3]

array([ 4, 15,  3])

In [ ]:
x1[2:4]

array([ 3, 12])

In [ ]:
#every other element, every 2 steps
x1[::2]

array([4, 3, 4])

In [ ]:
x2


array([[4, 3, 7, 5],
       [5, 0, 6, 5],
       [9, 3, 0, 5]])

In [ ]:
#two rows and three colums
x2[:2,:3]

array([[4, 3, 7],
       [5, 0, 6]])

# Reshaping of Arrays and Transpose

In [ ]:
grid = np.arange(1,10)
grid

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
grid.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
x = np.array([1,2,3])
x.shape

(3,)

In [ ]:
x.reshape(1,3).shape

(1, 3)

In [ ]:
x = np.arange(1,5, dtype = float)
x = x.reshape(2,2)
x

array([[1., 2.],
       [3., 4.]])

In [ ]:
x.T

array([[1., 3.],
       [2., 4.]])

# Array Concatenation and Splitting

In [ ]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [ ]:
np.concatenate((x,y), axis = 0)

array([1, 2, 3, 3, 2, 1])

In [ ]:
grid = np.array([[1,2,3],
               [4,5,6]])

In [ ]:
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.concatenate((grid,grid), axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [ ]:
#vstack
x = np.array([1,2,3])
grid = np.array([[9,8,7],
                 [6,5,4]])

In [ ]:
np.vstack((x, grid))

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [ ]:
#hstack
y = np.array([[99],
              [99]])
np.hstack((y, grid))

array([[99,  9,  8,  7],
       [99,  6,  5,  4]])

# Spliting of arrays

In [ ]:
x = np.array([1,2,3,99,69,3,2,1])

In [ ]:
x1, x2, x3 = np.split(x, [3,5])

In [ ]:
x1

array([1, 2, 3])

In [ ]:
x2

array([99, 69])

In [ ]:
x3

array([3, 2, 1])

# Broadcasting and Vectorised Operations

In [ ]:
a = np.arange(3)

In [ ]:
a+5 #Broadcasting

array([5, 6, 7])

In [ ]:
b = np.ones((3,3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
b + [0,1,2]

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [ ]:
c = np.arange(3).reshape(3,1)
c

array([[0],
       [1],
       [2]])

In [ ]:
a+c

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

# Manipulating & Comparing Array

#Aggregation
Aggregation = perform the same operation on a number of things

In [ ]:
list_number = [1,2,3]

In [ ]:
ll = np.array(list_number)

In [ ]:
ll

array([1, 2, 3])

In [ ]:
sum(ll) #Python sum()

6

In [ ]:
np.sum(ll) #Numpy sum()

6

In [ ]:
# Creatung a massive Numpy array
massive_array = np.random.random(10000)
massive_array[:5]
massive_array.shape

(10000,)

In [ ]:
%timeit sum(massive_array)  #Python builtin funtion sum()
%timeit np.sum(massive_array)  #Numpy's np.sum()

1000 loops, best of 5: 1.59 ms per loop
The slowest run took 15.41 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 9.9 µs per loop


Example about Standard Deviation and Variance

In [ ]:
dog_height = [600,470,170,430,300]

In [ ]:
dog_height = np.array(dog_height)

In [ ]:
np.std(dog_height)

147.32277488562318

In [ ]:
np.var(dog_height)

21704.0

# Sorting Arrays
np.sort uses an quicksort algorithm

In [ ]:
x = np.array([2,1,4,3,5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [ ]:
# sort by index
np.argsort(x)

array([1, 0, 3, 2, 4])

In [ ]:
np.random.seed(42)

MatA = np.random.randint(0,10, size=(4,6))

In [ ]:
MatA

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [ ]:
np.sort(MatA, axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [ ]:
np.sort(MatA, axis = 1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

# Linear Algebra

In [ ]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [ ]:
B = np.array([[6,5],
              [4,3],
              [2,1]])

In [ ]:
# A(3x3) dot product B(3x2)

In [ ]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

# Dot production Example

In [ ]:
# Number of jar sold
np.random.seed(0)

sales_amounts = np.random.randint(20, size = (5,3))

In [ ]:
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [ ]:
#Create weekly_sales DataFrame
import pandas as pd

weekly_sales = pd.DataFrame(sales_amounts, index = ["Mon", "Tues","Wed","Thurs", "Fri"],
                            columns = ["Aloumd Butter", "Peanut Butter", "Cashew Butter"])

In [ ]:
weekly_sales

Aloumd Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [ ]:
#create a price array
prices = np.array([10,8,12])

In [ ]:
butter_prices = pd.DataFrame(prices.reshape(1,3), index = ["Prices"], columns=["Aloumnd Butter", "Chanh", "Quat"])

In [ ]:
butter_prices

Aloumnd Butter  Chanh  Quat
Prices              10      8    12

In [ ]:
weekly_sales.shape, butter_prices.shape

((5, 3), (1, 3))

In [ ]:
cash = sales_amounts.dot(prices.T)

In [ ]:
cash

array([240, 138, 458, 232, 142])

In [ ]:
day_cash = pd.DataFrame(cash.reshape(1,5), index = ["Cash per day"], columns=["Mon", "Tues","Wed","Thurs", "Fri"])

In [ ]:
day_cash


Mon  Tues  Wed  Thurs  Fri
Cash per day  240   138  458    232  142

In [ ]:
weekly_sales["Totals Price"] = cash
weekly_sales

Aloumd Butter  Peanut Butter  Cashew Butter  Totals Price
Mon               12             15              0           240
Tues               3              3              7           138
Wed                9             19             18           458
Thurs              4              6             12           232
Fri                1              6              7           142